export const TiposDeTokens = {
  IF: 'IF',
  THEN: 'THEN',
  
  MAIS: 'MAIS',
  
  NUMERO_INTEIRO: 'NUMERO_INTEIRO',
  IDENTIFICADOR: 'IDENTIFICADOR',
  
  ESPACO_BRANCO: 'ESPACO_BRANCO',
  FIM_DE_ARQUIVO: 'FIM_DE_ARQUIVO',
  DESCONHECIDO: 'DESCONHECIDO'
};