export const TiposDeTokens = {
  // Palavras-chave
  PROGRAM: 'PROGRAM', VAR: 'VAR', CONST: 'CONST', TYPE: 'TYPE',
  BEGIN: 'BEGIN', END: 'END', IF: 'IF', THEN: 'THEN', ELSE: 'ELSE',
  WHILE: 'WHILE', DO: 'DO', FOR: 'FOR', TO: 'TO', REPEAT: 'REPEAT',
  UNTIL: 'UNTIL', FUNCTION: 'FUNCTION', PROCEDURE: 'PROCEDURE',

  // Tipos de dados
  INTEGER_TYPE: 'INTEGER_TYPE', REAL_TYPE: 'REAL_TYPE',

  // Operadores
  MAIS: 'MAIS', MENOS: 'MENOS', MULTIPLICACAO: 'MULTIPLICACAO', DIVISAO_REAL: 'DIVISAO_REAL',
  ATRIBUICAO: 'ATRIBUICAO', IGUAL: 'IGUAL', DIFERENTE: 'DIFERENTE',
  MENOR: 'MENOR', MENOR_IGUAL: 'MENOR_IGUAL', MAIOR: 'MAIOR', MAIOR_IGUAL: 'MAIOR_IGUAL',

  // Literais
  NUMERO_INTEIRO: 'NUMERO_INTEIRO',
  NUMERO_REAL: 'NUMERO_REAL',
  LITERAL_STRING: 'LITERAL_STRING',
  IDENTIFICADOR: 'IDENTIFICADOR',

  // Delimitadores
  PARENTESES_ESQ: 'PARENTESES_ESQ', PARENTESES_DIR: 'PARENTESES_DIR',
  PONTO_VIRGULA: 'PONTO_VIRGULA', DOIS_PONTOS: 'DOIS_PONTOS',
  PONTO: 'PONTO', VIRGULA: 'VIRGULA',

  // Ignoráveis e Controle
  COMENTARIO: 'COMENTARIO',
  ESPACO_BRANCO: 'ESPACO_BRANCO',
  FIM_DE_ARQUIVO: 'FIM_DE_ARQUIVO',
  DESCONHECIDO: 'DESCONHECIDO'
};